# Generated by Django 3.2.8 on 2022-01-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
            ],
            options={
                'verbose_name_plural': 'encabezados de facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='api.facturamaestro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
            options={
                'verbose_name_plural': 'detalles de facturas',
            },
        ),
    ]
